// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4WmlDr_u_ZX5LrHam-GvauvatwjUvTRE',
    appId: '1:1098281718895:web:ff06422480500b2c08e99a',
    messagingSenderId: '1098281718895',
    projectId: 'fifine',
    authDomain: 'fifine.firebaseapp.com',
    storageBucket: 'fifine.appspot.com',
    measurementId: 'G-4C7S49X792',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjOSSA27q-2Z8q1kj7SnqpxYahaWVNjw',
    appId: '1:1098281718895:android:3464062b8624821e08e99a',
    messagingSenderId: '1098281718895',
    projectId: 'fifine',
    storageBucket: 'fifine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIsydiMND7rLTti0qZAS353CLSGuNLHmo',
    appId: '1:1098281718895:ios:14fd5e0e9f67517808e99a',
    messagingSenderId: '1098281718895',
    projectId: 'fifine',
    storageBucket: 'fifine.appspot.com',
    androidClientId: '1098281718895-f3imn02klevqje4v8vp0837s0g8pg3hp.apps.googleusercontent.com',
    iosClientId: '1098281718895-2alitao50ik2orf25cm150d4olh4u9gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fifine',
  );
}
